config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :purchases, only: [:index, :create, :show]
  resources :load_funds_transactions

  resources :media

  get :store, to: 'stores#show', as: :default_store
  resources :stores, only: :show, param: :media_content_type

  get :library, to: 'libraries#show', as: :default_library
  resources :libraries, only: :show, param: :media_content_type

  namespace :admin do
    resources :purchases, only: [:index, :show]
    resources :media, only: [:index, :show, :destroy]
    resources :users, only: [:index, :show, :update]
  end

  root to: redirect('/store')

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if ENV_POLICY.allow?('LETTER_OPENER')
end

app/models/library.rb
class Library < ActiveRecord::Base
  belongs_to :user, validate: true

  validates_presence_of :user

  def media
    Medium.where(id: user.wallet.purchases.pluck(:medium_id))
  end

  def has?(medium)
    media.exists?(medium)
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < AuthenticatedController
  def show
    @library = library_view
  end

  private

  def library_view
    MediaView.new(
      media_scope: library.media,
      media_content_type: media_content_type_param,
      search_term: search_term_param
    )
  end

  def search_term_param
    params[:search_term]
  end

  def library
    current_user.library
  end

  def category_id_param
    params[:category_id]
  end

  def media_content_type_param
    params.fetch(:media_content_type, Medium::BOOK)
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_for(@library) do |f| %>
  <% if @library.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% @library.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form' %>

<%= link_to 'Show', @library %>

app/views/libraries/index.html.erb
<%= flash_messages %>

<h1>Listing Libraries</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.user %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form' %>

app/views/libraries/show.html.erb
<%= flash_messages %>

<h1>Library</h1>

<%= categories_select(@library, path_helper: method(:library_path)) %>

<%= render partial: 'media/cards_display', locals: { media_view: @library } %>