config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :purchases, only: [:index, :create, :show]
  resources :load_funds_transactions

  resources :media

  get :store, to: 'stores#show', as: :default_store
  resources :stores, only: :show, param: :media_content_type

  get :library, to: 'libraries#show', as: :default_library
  resources :libraries, only: :show, param: :media_content_type

  namespace :admin do
    resources :purchases, only: [:index, :show]
    resources :media, only: [:index, :show, :destroy]
    resources :users, only: [:index, :show, :update]
  end

  root to: redirect('/store')

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if ENV_POLICY.allow?('LETTER_OPENER')
end

app/controllers/load_funds_transactions_controller.rb
class LoadFundsTransactionsController < AuthenticatedController
  before_action :set_load_funds_transaction, only: [:show]

  # GET /load_funds_transactions
  def index
    @load_funds_transactions = scope.ordered
  end

  # GET /load_funds_transactions/1
  def show
  end

  # GET /load_funds_transactions/new
  def new
    @load_funds_transaction = scope.new
  end

  # POST /load_funds_transactions
  def create
    response = LoadFunds.new.(
      user: current_user,
      amount: amount_param
    )

    @load_funds_transaction = response.load_funds_transaction

    if response.success?
      redirect_to @load_funds_transaction, notice: 'Load funds transaction was successfully created.'
    else
      render :new
    end
  end

  private

  def scope
    current_user.wallet.load_funds_transactions
  end

  def set_load_funds_transaction
    @load_funds_transaction = scope.find(params[:id])
  end

  def amount_param
    load_funds_transaction_params[:amount]
  end

  def load_funds_transaction_params
    params.require(:load_funds_transaction).permit(:amount)
  end
end

app/helpers/load_funds_transactions_helper.rb
module LoadFundsTransactionsHelper
end

app/views/load_funds_transactions/_form.html.erb
<%= form_for(@load_funds_transaction) do |f| %>
  <% if @load_funds_transaction.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
          <%= pluralize(@load_funds_transaction.errors.count, "error") %> prohibited this load_funds_transaction from being saved:
          <ul>
          <% @load_funds_transaction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :amount %>
    <div class="input-group">
        <%= f.number_field :amount, class: 'form-control' %>
        <div class="input-group-btn">
            <%= f.submit class: 'btn btn-success' %>
        </div>
  </div>
<% end %>

app/views/load_funds_transactions/index.html.erb
<%= flash_messages %>

<h1>Listing Load Funds Transactions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Date</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @load_funds_transactions.each do |load_funds_transaction| %>
      <tr>
        <td><%= humanized_money_with_symbol load_funds_transaction.amount %></td>
        <td><%= humanized_date load_funds_transaction.created_at %></td>
        <td><%= link_to 'Show', load_funds_transaction %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Load funds transaction', new_load_funds_transaction_path %>

app/views/load_funds_transactions/new.html.erb
<h1>New Load Funds Transaction</h1>

<%= render 'form' %>

app/views/load_funds_transactions/show.html.erb
<%= flash_messages %>
<%= link_to 'Go Back', load_funds_transactions_path, class: 'btn btn-primary pull-sm-right' %>
<dl>
    <dt>Amount</dt>
    <dd><%= humanized_money_with_symbol @load_funds_transaction.amount %></dd>
    <dt>Date</dt>
    <dd><%= humanized_date @load_funds_transaction.created_at %></dd>
</dl>