config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :purchases, only: [:index, :create, :show]
  resources :load_funds_transactions

  resources :media

  get :store, to: 'stores#show', as: :default_store
  resources :stores, only: :show, param: :media_content_type

  get :library, to: 'libraries#show', as: :default_library
  resources :libraries, only: :show, param: :media_content_type

  namespace :admin do
    resources :purchases, only: [:index, :show]
    resources :media, only: [:index, :show, :destroy]
    resources :users, only: [:index, :show, :update]
  end

  root to: redirect('/store')

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if ENV_POLICY.allow?('LETTER_OPENER')
end

app/helpers/layouts_helper.rb
module LayoutsHelper
  # Used to achieve nested layouts without content_for. This helper relies on
  # Rails internals, so beware that it make break with future major versions
  # of Rails. Inspired by http://stackoverflow.com/a/18214036
  #
  # Usage: For example, suppose "child" layout extends "parent" layout.
  # Use <%= yield %> as you would with non-nested layouts, as usual. Then on
  # the very last line of layouts/child.html.erb, include this:
  #
  #     <% parent_layout "parent" %>
  #
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>uniTunes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">

  <%# <link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0-alpha.2/readable/bootstrap.min.css" rel="stylesheet" integrity="sha384-/x/+iIbAU4qS3UecK7KIjLZdUilKKCjUFVdwFx8ba7S/WvxbrYeQuKEt0n/HWqTx" crossorigin="anonymous"> %>
</head>
<body>

  <%= yield :header %>

  <main>
    <%= content_for?(:content) ? yield(:content) : yield %>
  </main>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.3/holder.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js" integrity="sha384-vZ2WRJMwsjRMW/8U7i6PWi6AlO1L79snBrmgiDpgIWJ82z8eA5lenwvxbMV1PAh7" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/authenticated.html.erb
<% content_for :header do %>
  <nav class="navbar navbar-dark bg-inverse">

    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to 'uniTunes', root_path, class: 'navbar-brand' %></li>
      <li class="nav-item"><%= link_to 'Store', default_store_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Library', default_library_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Purchase History', purchases_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Portfolio', media_path, class: 'nav-link' %></li>
    </ul>

    <div class="pull-xs-right">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <%= link_to account_balance, load_funds_transactions_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

<%= render template: 'layouts/application' %>

app/views/layouts/libraries.html.erb
<% content_for :content do %>
  <%= render partial: 'media_content_types_nav', locals: { path_helper: method(:library_path) } %>

  <%= content_for?(:libraries_content) ? yield(:libraries_content) : yield %>
<% end %>

<%= render template: 'layouts/authenticated' %>

app/views/layouts/media.html.erb
<% content_for :content do %>
  <%= content_for?(:media_content) ? yield(:media_content) : yield %>
<% end %>

<%= render template: 'layouts/authenticated' %>

app/views/layouts/stores.html.erb
<% content_for :content do %>
  <%= render partial: 'media_content_types_nav', locals: { path_helper: method(:store_path) } %>

  <%= content_for?(:stores_content) ? yield(:stores_content) : yield %>
<% end %>

<%= render template: 'layouts/authenticated' %>